name: Build Tutorial PDF
on:
  push:
    branches:
      - "main"
    paths:
      - "tutorial/**.md"
      - "tutorial/images/**"
permissions:
  contents: write
jobs:
  ConvertToPDF:
    name: Markdown to PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: tutorial
          output_dir: tutorial_pdf
          images_dir: images
          image_import: ./images
          build_html: false
      - name: Config GIT
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@restorelab.co.nz"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Build latest tutorial PDF"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main